DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Bid;
DROP TABLE IF EXISTS User;

CREATE TABLE User(
  UserID TEXT PRIMARY KEY,
  Rating REAL NOT NULL,
  Location TEXT,
  Country TEXT
);

CREATE TABLE Item(
  ItemID INTEGER PRIMARY KEY,
  SellerID TEXT NOT NULL,
  Name TEXT NOT NULL,
  Current REAL NOT NULL,
  FirstBid REAL NOT NULL,
  NumberOfBids INTEGER NOT NULL,
  Started TEXT NOT NULL,
  Ends TEXT NOT NULL,
  Description TEXT NOT NULL,
  BuyPrice REAL,
  FOREIGN KEY(SellerID) REFERENCES User(UserID)
);

CREATE TABLE Category(
  ItemID INTEGER NOT NULL,
  NAME TEXT NOT NULL,
  FOREIGN KEY(ItemID) REFERENCES User(ItemID)
);

CREATE TABLE Bid(
  ItemID INTEGER NOT NULL,
  BidderID TEXT NOT NULL,
  Time TEXT NOT NULL,
  Amount REAL NOT NULL,
  FOREIGN KEY(ItemID) REFERENCES User(ItemID),
  FOREIGN KEY(BidderID) REFERENCES User(UserID)
);


